# PBS configuration
queue: normalbw
project: x77
walltime: 6:00:00
jobname: 1deg_jra55_ryf
ncpus: 252
mem: 500GB

shortpath: /short/x77

# Model configuration
model: access-om2
submodels:
    - name: atmosphere
      model: matm
      exe: matm_jra55_86e1835a.exe
      ncpus: 1

    - name: ocean
      model: mom
      exe: fms_ACCESS-OM_61841471.x
      input: mom_1deg
      timestep: 5400
      ncpus: 216

    - name: ice
      model: cice5
      exe: cice_auscom_360x300_24p_c612c0dd.exe
      input: cice_1deg
      timestep: 5400
      ncpus: 24

    - name: coupler
      model: oasis
      input: oasis_jra55_to_1deg
      timestep: 5400
      ncpus: 0


calendar:
    runtime:
        years: 20
        months: 0
        days: 0

    start:
        year: 1
        month: 1
        days: 1

platform:
    nodesize: 28

# Misc
runlog: False
stacksize: unlimited
collate_walltime: 1:00:00
collate_queue: express
collate_ncpus: 1
collate_flags: -n4 -z -m -r
mpirun: --mca orte_base_help_aggregate 0
qsub_flags: -lother=hyperthread -W umask=027
# postscript: sync_output_to_gdata.sh
