# PBS configuration
queue: normalbw
project: x77
walltime: 6:00:00
jobname: 1deg_jra55_ryf
ncpus: 252
mem: 500GB

shortpath: /short/x77

# Model configuration
model: access-om2
input: global_input
submodels:
    - name: atmosphere
      model: yatm
      exe: yatm.exe
      input: yatm
      ncpus: 1

    - name: ocean
      model: mom
      exe: fms_ACCESS-OM.x
      input: mom_1deg
      ncpus: 216

    - name: ice
      model: cice5
      exe: cice_auscom_360x300_24p.exe
      input: cice_1deg
      ncpus: 24

platform:
    nodesize: 28

# Misc
runlog: False
stacksize: unlimited
collate_walltime: 1:00:00
collate_queue: express
collate_ncpus: 1
collate_flags: -n4 -z -m -r
mpirun: --mca orte_base_help_aggregate 0
qsub_flags: -lother=hyperthread -W umask=027
# postscript: sync_output_to_gdata.sh
