# PBS configuration
queue: normalbw
project: x77
walltime: 4:00:00
jobname: 1deg_jra55_ryf
ncpus: 252
mem: 500GB

shortpath: /short/x77

# Model configuration
name: common
model: access-om2
input: /short/public/access-om2/input_08022019/common_1deg_jra55
submodels:
    - name: atmosphere
      model: yatm
      exe: /short/public/access-om2/bin/yatm_b77aecd.exe
      input: /short/public/access-om2/input_08022019/yatm_1deg
      ncpus: 1

    - name: ocean
      model: mom
      exe: /short/public/access-om2/bin/fms_ACCESS-OM_3b6775a_libaccessom2_b77aecd.x
      input: /short/public/access-om2/input_08022019/mom_1deg
      ncpus: 216

    - name: ice
      model: cice5
      exe: /short/public/access-om2/bin/cice_auscom_360x300_24p_657f6ad_libaccessom2_b77aecd.exe
      input: /short/public/access-om2/input_08022019/cice_1deg
      ncpus: 24

platform:
    nodesize: 28

# Misc
runlog: True
stacksize: unlimited
collate_walltime: 1:00:00
collate_queue: express
collate_mem: 4GB
collate_ncpus: 1
collate_flags: -n4 -z -m -r
mpirun: --mca orte_base_help_aggregate 0
qsub_flags: -lother=hyperthread -W umask=027
# postscript: sync_output_to_gdata.sh
