# PBS configuration
queue: express
walltime: 4:00:00
jobname: 1deg_jra55_ryf
ncpus: 252
mem: 500GB
# Model configuration
name: common
model: access-om2
input: /g/data4/ik11/inputs/access-om2/input_236a3011/common_1deg_jra55
submodels:
    - name: atmosphere
      model: yatm
      exe: /g/data4/ik11/inputs/access-om2/bin/yatm_17bed6f.exe
      input: 
            - /g/data4/ik11/inputs/access-om2/input_236a3011/yatm_1deg
            - /g/data1a/ua8/JRA55-do/RYF/v1-3/
      ncpus: 1

    - name: ocean
      model: mom
      exe: /g/data4/ik11/inputs/access-om2/bin/fms_ACCESS-OM_66a3e59_libaccessom2_17bed6f.x
      input: /g/data4/ik11/inputs/access-om2/input_236a3011/mom_1deg
      ncpus: 216

    - name: ice
      model: cice5
      exe: /g/data4/ik11/inputs/access-om2/bin/cice_auscom_360x300_24p_b37ea14_libaccessom2_17bed6f.exe
      input: /g/data4/ik11/inputs/access-om2/input_236a3011/cice_1deg
      ncpus: 24

# Collation
collate:
  walltime: 1:00:00
  mem: 30GB
  ncpus: 4
  queue: express
  exe: /g/data4/ik11/inputs/access-om2/bin/mppnccombine

# Misc
runlog: True
stacksize: unlimited
mpirun: --mca orte_base_help_aggregate 0
qsub_flags: -lother=hyperthread -W umask=027
platform:
    nodesize: 48
# postscript: sync_output_to_gdata.sh
