# PBS configuration
queue: normalbw
project: x77
walltime: 1:00:00
jobname: 1deg_jra55_ryf
ncpus: 252
mem: 500GB

shortpath: /short/x77

# Model configuration
name: common
model: access-om2
input: /short/public/access-om2/input_38570c62/common_1deg_jra55
submodels:
    - name: atmosphere
      model: yatm
      exe: /short/public/access-om2/bin/yatm_e8ad3723.exe
      input: /short/public/access-om2/input_38570c62/yatm_1deg
      ncpus: 1

    - name: ocean
      model: mom
      exe: /short/public/access-om2/bin/fms_ACCESS-OM_afe80bfd.x
      input: /short/public/access-om2/input_38570c62/mom_1deg
      ncpus: 216

    - name: ice
      model: cice5
      #exe: /short/public/access-om2/bin/cice_auscom_360x300_24p_2ff1ea66.exe
      exe: /short/public/access-om2/bin/cice_auscom_360x300_24p_076b14f2.exe
      input: /short/public/access-om2/input_38570c62/cice_1deg
      ncpus: 24

platform:
    nodesize: 28

# Misc
runlog: False
stacksize: unlimited
collate_walltime: 1:00:00
collate_queue: express
collate_ncpus: 1
collate_flags: -n4 -z -m -r
mpirun: --mca orte_base_help_aggregate 0
qsub_flags: -lother=hyperthread -W umask=027
# postscript: sync_output_to_gdata.sh
