# PBS configuration

# If submitting to a different project to your default, uncomment line below 
# and change project code as appropriate; also set shortpath below
# project: v45

# Force payu to always find, and save, files in this scratch project directory
# (you may need to add the corresponding PBS -l storage flag in sync_data.sh)
# shortpath: /scratch/v45

queue: normal
walltime: 3:00:00
jobname: 1deg_jra55_ryf
mem: 1000GB

# Model configuration
name: common
model: access-om2
input: /g/data/ik11/inputs/access-om2/input_20201102/common_1deg_jra55
submodels:
    - name: atmosphere
      model: yatm
      exe: /g/data/ik11/inputs/access-om2/bin/yatm_44e8821.exe
      input:
            - /g/data/ik11/inputs/access-om2/input_20201102/yatm_1deg
            - /g/data/ik11/inputs/JRA-55/RYF/v1-4
      ncpus: 1

    - name: ocean
      model: mom
      exe: /g/data/ik11/inputs/access-om2/bin/fms_ACCESS-OM-BGC_af3a94d_libaccessom2_44e8821.x
      input: /g/data/ik11/inputs/access-om2/input_20201102/mom_1deg
      ncpus: 216

    - name: ice
      model: cice5
      exe: /g/data/ik11/inputs/access-om2/bin/cice_auscom_360x300_24p_dfb833a_libaccessom2_44e8821.exe
      input: /g/data/ik11/inputs/access-om2/input_20201102/cice_1deg
      ncpus: 24

# Collation
collate:
  restart: true
  walltime: 1:00:00
  mem: 30GB
  ncpus: 4
  queue: normal
  exe: /g/data/ik11/inputs/access-om2/bin/mppnccombine

# Misc
runlog: true
stacksize: unlimited
restart_freq: 1  # use tidy_restarts.py instead
mpirun: --mca io ompio --mca io_ompio_num_aggregators 1
qsub_flags: -W umask=027
# set number of cores per node (28 for normalbw, 48 for normal on gadi)
platform:
    nodesize: 48
# sweep and resubmit on specific errors - see https://github.com/payu-org/payu/issues/241#issuecomment-610739771
userscripts:
    error: resub.sh
    run: rm -f resubmit.count

# DANGER! Do not uncomment this without checking the script is syncing to the correct location!
# postscript: sync_data.sh
