format: yamanifest
version: 1.0
---
work/atmosphere/yatm.exe:
  fullpath: /g/data/vk83/prerelease/apps/spack/0.22/release/linux-rocky8-x86_64/intel-19.0.5.281/libaccessom2-git.2025.05.001_access-om2-vhhq7nklvbokasnvs3yit3qkla4jwzm5/bin/yatm.exe
  hashes:
    binhash: 738859af4333323d3711592a84def5dd
    md5: 71c438389384bcaa4e8c429ca7f8d08c
work/ice/cice_auscom_360x300_24x1_24p.exe:
  fullpath: /g/data/vk83/prerelease/apps/spack/0.22/release/linux-rocky8-x86_64/intel-19.0.5.281/cice5-git.2025.03.001_access-om2-nadfb72vzkskufeexdprjkermz7joa32/bin/cice_auscom_360x300_24x1_24p.exe
  hashes:
    binhash: ce09d2c54ecbd98f8357502b857f2637
    md5: a67a49e4346683749e5ef5912a2e56c5
work/ocean/mom5_access_om:
  fullpath: /g/data/vk83/prerelease/apps/spack/0.22/release/linux-rocky8-x86_64/intel-19.0.5.281/mom5-git.2025.05.000_access-om2-zs2u7dppke6qfh2fzzhp5khu5fdi4f4j/bin/mom5_access_om
  hashes:
    binhash: 21e69f4ddde51b03a0aae4a603e5483e
    md5: 3fba50865ece6abcfbeb93b588479a3d
