format: yamanifest
version: 1.0
---
work/atmosphere/yatm.exe:
  fullpath: /g/data/tm70/as2285/spack/om2/release/linux-rocky8-x86_64/intel-19.0.5.281/libaccessom2-git.2025.05.001_access-om2-qyg6xj4req4rz6wbnfwfxdnohvenibzz/bin/yatm.exe
  hashes:
    binhash: 71db2f3a770245039c392da212b05395
    md5: 4a5e0174bb5afe46cd6b1fd5db9104a0
work/ice/cice_auscom_360x300_15x300.exe:
  fullpath: /g/data/tm70/as2285/spack/om2/release/linux-rocky8-x86_64/intel-19.0.5.281/cice5-stable-owq2spgevuhutlni7jfvbzefd62ucbkf/bin/cice_auscom_360x300_15x300.exe
  hashes:
    binhash: b3cdf0a971cbdf282d73dfc23e2142f8
    md5: bc4d51b4e77ebc0ef2b36657e9900b15
work/ocean/mom5_access_om:
  fullpath: /g/data/tm70/as2285/spack/om2/release/linux-rocky8-x86_64/intel-19.0.5.281/mom5-git.2025.08.000_access-om2-b75grr7zhbqsybkco7hogj7ny72pbkwc/bin/mom5_access_om
  hashes:
    binhash: 4c7fed85f3cc4a26d006830021ed8f86
    md5: 9e9ebf99242516ae1df3c41d10158897
