format: yamanifest
version: 1.0
---
work/atmosphere/yatm.exe:
  fullpath: /g/data/vk83/prerelease/apps/spack/0.22/release/linux-rocky8-x86_64/intel-19.0.5.281/libaccessom2-git.2025.05.001_access-om2-qsfaprbjmfmj7dwmts3ml647mlm276xh/bin/yatm.exe
  hashes:
    binhash: ea1a943c684c99955aaf1a8b48b88a48
    md5: a8344af515baf96bbec27d0d32ffe3bf
work/ice/cice_auscom_360x300_15x300.exe:
  fullpath: /g/data/vk83/prerelease/apps/spack/0.22/release/linux-rocky8-x86_64/intel-19.0.5.281/cice5-git.38b7fc85382ec1015fb7304bb3c9e2ba6e2e9a0f_stable-5zr46y3syjqpylqk5oj4vicbh6x6ysjv/bin/cice_auscom_360x300_15x300.exe
  hashes:
    binhash: becf02da9b33691edd7ebe0539f33f28
    md5: fb0fd0c9da6c469aec817cc6840fa2c9
work/ocean/mom5_access_om:
  fullpath: /g/data/vk83/prerelease/apps/spack/0.22/release/linux-rocky8-x86_64/intel-19.0.5.281/mom5-git.2025.08.000_access-om2-kpkemvtusoritgrwygchrrqdifsypfy4/bin/mom5_access_om
  hashes:
    binhash: 4d0695998fcde5d0c1d96d8abc5c2a75
    md5: b0de9991c39bb963fb9609bf2f17c2f3
