format: yamanifest
version: 1.0
---
work/atmosphere/yatm.exe:
  fullpath: /g/data/vk83/apps/spack/0.22/release/linux-rocky8-x86_64/intel-19.0.5.281/libaccessom2-git.2025.05.001_access-om2-4twfnozajgiintncd2kpbw6ix5u42na3/bin/yatm.exe
  hashes:
    binhash: f40e5509daecf5078e3d3ea53243150d
    md5: 048284ea6d59604548580beef76fe870
work/ice/cice_auscom_360x300_24x1_24p.exe:
  fullpath: /g/data/vk83/apps/spack/0.22/release/linux-rocky8-x86_64/intel-19.0.5.281/cice5-git.2025.03.001_access-om2-vhnfg6zthzsb5g5aziwkls7xlpogg6ki/bin/cice_auscom_360x300_24x1_24p.exe
  hashes:
    binhash: ad3cbce14a4edaf36bfee50dcbabee4a
    md5: 23b61d623b457b076d1b9bc392fe289d
work/ocean/mom5_access_om:
  fullpath: /g/data/vk83/apps/spack/0.22/release/linux-rocky8-x86_64/intel-19.0.5.281/mom5-git.2025.08.000_access-om2-2ix4rqzaomgou7c44uisb5pvssbwzlfr/bin/mom5_access_om
  hashes:
    binhash: 3738f4c55a8084f30c244c1919109cb4
    md5: a806d75628abdfb3a622fcaeb9bc5c59
