format: yamanifest
version: 1.0
---
work/INPUT/rmp_jra55_cice_1st_conserve.nc:
  fullpath: /g/data/vk83/experiments/inputs/access-om2/remapping_weights/JRA55/global.01deg/2020.05.30/rmp_jra55_cice_1st_conserve.nc
  hashes:
    binhash: c7710f6bfdf6221c8bca405d07b1bf70
    md5: 16d69cca9d8e327ffa99f6569c857096
work/INPUT/rmp_jra55_cice_2nd_conserve.nc:
  fullpath: /g/data/vk83/experiments/inputs/access-om2/remapping_weights/JRA55/global.01deg/2020.05.30/rmp_jra55_cice_2nd_conserve.nc
  hashes:
    binhash: cc9701ab595d9676ab7d1fc28a7befab
    md5: 43349f57a2fdaec9556bf7b6a51e3978
work/INPUT/rmp_jra55_cice_patch.nc:
  fullpath: /g/data/vk83/experiments/inputs/access-om2/remapping_weights/JRA55/global.01deg/2020.05.30/rmp_jra55_cice_patch.nc
  hashes:
    binhash: 96fc5d2ffa46b14e4369d8e1a1cee1fc
    md5: 3d62f2c7dbbf18734bdb2f7395daa607
work/atmosphere/INPUT/RYF.friver.1990_1991.nc:
  fullpath: /g/data/vk83/experiments/inputs/JRA-55/RYF/v1-4/data/RYF.friver.1990_1991.nc
  hashes:
    binhash: df5b6715e020f563acb65673571a565f
    md5: fa3a55aeb6706a1b422d096f61a772c1
work/atmosphere/INPUT/RYF.huss.1990_1991.nc:
  fullpath: /g/data/vk83/experiments/inputs/JRA-55/RYF/v1-4/data/RYF.huss.1990_1991.nc
  hashes:
    binhash: 71d6099511ebc8b43f9b86b325ecf3af
    md5: 6032d514fdfdd2b6a84bdef0a4ac3afe
work/atmosphere/INPUT/RYF.licalvf.1990_1991.nc:
  fullpath: /g/data/vk83/experiments/inputs/JRA-55/RYF/v1-4/data/RYF.licalvf.1990_1991.nc
  hashes:
    binhash: f219ce98f3fcbe6f8ec517740f01aee1
    md5: 6f927702cbc023cc20d3ddd69695f0a0
work/atmosphere/INPUT/RYF.prra.1990_1991.nc:
  fullpath: /g/data/vk83/experiments/inputs/JRA-55/RYF/v1-4/data/RYF.prra.1990_1991.nc
  hashes:
    binhash: 2754bd49fff02bf5330a086310f1c296
    md5: ac199086106ec4e41506e6082bccb109
work/atmosphere/INPUT/RYF.prsn.1990_1991.nc:
  fullpath: /g/data/vk83/experiments/inputs/JRA-55/RYF/v1-4/data/RYF.prsn.1990_1991.nc
  hashes:
    binhash: 154a15cde4940309ac5e6fef0d7faba4
    md5: cd076c877c2c5df61615e04d71ed00e0
work/atmosphere/INPUT/RYF.psl.1990_1991.nc:
  fullpath: /g/data/vk83/experiments/inputs/JRA-55/RYF/v1-4/data/RYF.psl.1990_1991.nc
  hashes:
    binhash: 559b1e3183475cfb94a7f013f4acf8ea
    md5: 0dfd94a5c3234fd2016dfdd01e84a170
work/atmosphere/INPUT/RYF.rhuss.1990_1991.nc:
  fullpath: /g/data/vk83/experiments/inputs/JRA-55/RYF/v1-4/data/RYF.rhuss.1990_1991.nc
  hashes:
    binhash: 1f70c237032f7368e6f2478d2a678c99
    md5: 632519955305cb5c19e286b151439fb5
work/atmosphere/INPUT/RYF.rlds.1990_1991.nc:
  fullpath: /g/data/vk83/experiments/inputs/JRA-55/RYF/v1-4/data/RYF.rlds.1990_1991.nc
  hashes:
    binhash: 9512836673a68507bed403ecd859ba38
    md5: 0ea83e107ec883c3f39a12b60ff50d8e
work/atmosphere/INPUT/RYF.rsds.1990_1991.nc:
  fullpath: /g/data/vk83/experiments/inputs/JRA-55/RYF/v1-4/data/RYF.rsds.1990_1991.nc
  hashes:
    binhash: 7ff7cd79ace33fefe2b9a91ea018ea14
    md5: b74bf123f1e4557368a61732cf24f1c2
work/atmosphere/INPUT/RYF.tas.1990_1991.nc:
  fullpath: /g/data/vk83/experiments/inputs/JRA-55/RYF/v1-4/data/RYF.tas.1990_1991.nc
  hashes:
    binhash: 8f3c6798cc92a1d0b6573eb44b2a4dd2
    md5: 06689885f4f2f726b95a2818ab78a20d
work/atmosphere/INPUT/RYF.uas.1990_1991.nc:
  fullpath: /g/data/vk83/experiments/inputs/JRA-55/RYF/v1-4/data/RYF.uas.1990_1991.nc
  hashes:
    binhash: 54ede2172bf85bc861bc64c296a03f8c
    md5: 107bf9480f55597655d2d283b6f6b4ff
work/atmosphere/INPUT/RYF.vas.1990_1991.nc:
  fullpath: /g/data/vk83/experiments/inputs/JRA-55/RYF/v1-4/data/RYF.vas.1990_1991.nc
  hashes:
    binhash: 17224eecb745b6ce72604b41201c1fe7
    md5: 88dc8c70338bbc8f5efc48ed0009a99f
work/atmosphere/INPUT/rmp_jrar_to_cict_CONSERV.nc:
  fullpath: /g/data/vk83/experiments/inputs/access-om2/remapping_weights/JRA55/global.01deg/2020.05.30/rmp_jrar_to_cict_CONSERV.nc
  hashes:
    binhash: 16b59e31f2618d9b4df7e907dc11fb25
    md5: 08f3f762a1b005d4ba90f5ceef5ccc74
work/ice/RESTART/grid.nc:
  copy: true
  fullpath: /g/data/vk83/experiments/inputs/access-om2/ice/grids/global.01deg/2024.04.17/grid.nc
  hashes:
    binhash: d71c0256388855eb6c2e7ab27997fdde
    md5: ab3458bf0c16cc5e2e72f59b705de313
work/ice/RESTART/i2o.nc:
  copy: true
  fullpath: /g/data/vk83/experiments/inputs/access-om2/ice/initial_conditions/global.01deg/2020.05.30/i2o.nc
  hashes:
    binhash: c28de3c40c243977d02a6d4672807038
    md5: a118ccf1a07bf31676e038e3c2b6c964
work/ice/RESTART/kmt.nc:
  copy: true
  fullpath: /g/data/vk83/experiments/inputs/access-om2/ice/grids/global.01deg/2024.04.17/kmt.nc
  hashes:
    binhash: f17083b7d13413de60466ba220b05860
    md5: 8c12f286b56ff171287753986e72d5cb
work/ice/RESTART/monthly_sstsss.nc:
  copy: true
  fullpath: /g/data/vk83/experiments/inputs/access-om2/ice/initial_conditions/global.01deg/2020.05.30/monthly_sstsss.nc
  hashes:
    binhash: 59d46726887afc66225c8bdfa6a25d5b
    md5: e00d77cf7b519d9bbcfc8bea2e34ef8f
work/ice/RESTART/o2i.nc:
  copy: true
  fullpath: /g/data/vk83/experiments/inputs/access-om2/ice/initial_conditions/global.01deg/2020.05.30/o2i.nc
  hashes:
    binhash: 8ea25776dc6684070214a9f1e041b114
    md5: a08c3c2c2f7668732f64347adc6c20cb
work/ice/RESTART/u_star.nc:
  copy: true
  fullpath: /g/data/vk83/experiments/inputs/access-om2/ice/initial_conditions/global.01deg/2020.05.30/u_star.nc
  hashes:
    binhash: 6eae42f2ab0164f2b3df10292649abae
    md5: e34bf0c92d0585cfc2d90de32af35e43
work/ocean/INPUT/chl.nc:
  fullpath: /g/data/vk83/experiments/inputs/access-om2/ocean/chlorophyll/global.01deg/2020.05.30/chl.nc
  hashes:
    binhash: c33b83b1f3f3b92ab7390b4c9888820f
    md5: 8cc506303102f2faad01b8ffb5268bf5
work/ocean/INPUT/grid_spec.nc:
  fullpath: /g/data/vk83/experiments/inputs/access-om2/ocean/grids/mosaic/global.01deg/2020.05.30/grid_spec.nc
  hashes:
    binhash: 22d51e6d15b1247123786da5e0672578
    md5: cb5674cf1d2be64b3c5c1eac948e51d7
work/ocean/INPUT/ocean_hgrid.nc:
  fullpath: /g/data/vk83/experiments/inputs/access-om2/ocean/grids/mosaic/global.01deg/2020.05.30/ocean_hgrid.nc
  hashes:
    binhash: 282a7825f7adaeb85c5ba0960eac23ed
    md5: c6d7acf7fe7d6df5d5b72ebf37d11f90
work/ocean/INPUT/ocean_mask.nc:
  fullpath: /g/data/vk83/experiments/inputs/access-om2/ocean/grids/bathymetry/global.01deg/2020.05.30/ocean_mask.nc
  hashes:
    binhash: f4d3075cdf2f573ec35e0b8ba3084840
    md5: 7868653fbcc22b1654a6ace0e3b15763
work/ocean/INPUT/ocean_mask_table:
  fullpath: /g/data/vk83/experiments/inputs/access-om2/ocean/processor_masks/global.01deg/4358.80x75/2020.05.30/ocean_mask_table
  hashes:
    binhash: 0d7bf8ddaed8d64b2bc51ab9abfb548c
    md5: baca6cd1163063135e0fcb3c343bb5e6
work/ocean/INPUT/ocean_mosaic.nc:
  fullpath: /g/data/vk83/experiments/inputs/access-om2/ocean/grids/mosaic/global.01deg/2020.05.30/ocean_mosaic.nc
  hashes:
    binhash: 76f3b517569d70bd5d2e50acc1f6aa8e
    md5: 1263df68b94e7a256be52283df611e94
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /g/data/vk83/experiments/inputs/access-om2/ocean/initial_conditions/global.01deg/2020.10.22/ocean_temp_salt.res.nc
  hashes:
    binhash: 632af80792f66b78a0bc95f53eb8a988
    md5: 7e3671bdd8e1732b55eb3f9eeb5f614a
work/ocean/INPUT/ocean_vgrid.nc:
  fullpath: /g/data/vk83/experiments/inputs/access-om2/ocean/grids/vertical/global.01deg/2020.05.30/ocean_vgrid.nc
  hashes:
    binhash: 6702a7ca40775e2722264d372aa1ffbb
    md5: 31d7de8345a0bab0ee004915aa36027a
work/ocean/INPUT/roughness_amp.nc:
  fullpath: /g/data/vk83/experiments/inputs/access-om2/ocean/tides/global.01deg/2020.05.30/roughness_amp.nc
  hashes:
    binhash: 650dc6489e1b3785813dba278f177dc9
    md5: f13792f9f45097086da030ff83035f27
work/ocean/INPUT/roughness_cdbot.nc:
  fullpath: /g/data/vk83/experiments/inputs/access-om2/ocean/tides/global.01deg/2020.05.30/roughness_cdbot.nc
  hashes:
    binhash: 6ca7d157175d4550e81ab57aeb7f7684
    md5: a690972610c4d6c20388f44bde3e9837
work/ocean/INPUT/salt_sfc_restore.nc:
  fullpath: /g/data/vk83/experiments/inputs/access-om2/ocean/surface_salt_restoring/global.01deg/2020.05.30/salt_sfc_restore.nc
  hashes:
    binhash: fd2784b76ceae2dedcfe2e0d12978b44
    md5: 61bff26084d7efa9423bb14fe3bc9347
work/ocean/INPUT/tideamp.nc:
  fullpath: /g/data/vk83/experiments/inputs/access-om2/ocean/tides/global.01deg/2020.05.30/tideamp.nc
  hashes:
    binhash: ca509f32cc8305cd186b9f2eabe8bfbb
    md5: 92a791452244947a7a393e8ff489c5bb
work/ocean/INPUT/topog.nc:
  fullpath: /g/data/vk83/experiments/inputs/access-om2/ocean/grids/bathymetry/global.01deg/2020.05.30/topog.nc
  hashes:
    binhash: faa894b0c4b078205b05a75d4ee654c2
    md5: 1e69c16bd3a2fd335a746ff30fe7cc84
